- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2:
        instance_type: t2.small
        image: ami-061ac2e015473fbe2
        region: us-east-1
        key_name: devops
        vpc_subnet_id: subnet-02a69e3eba685265b
        assign_public_ip: yes
        count: 1
        group: eshop
        wait: true
#        aws_access_key: ${{ secrets.ACCESS_KEY }}
#        aws_secret_key: ${{ secrets.SECRET_KEY }}
#        security_token: ${{ secrets.SESSION_TOKEN }}
        aws_access_key: "ASIA52NP3MZ6DNIJYQNZ"
        aws_secret_key: "3Z7YSWf8X2/6ylt5HUay7mHxBXJCu9mmDPhlUkix"
        security_token: "FwoGZXIvYXdzEDUaDGgpg+F4lOYyJ6SiFCK3ATrqsWbzXN7GjPUPA/FNUZcUZcfeVqrTMo8ApaaLFKYz+WEW0JXzEPl0PNsknxyRwSbhxpibsmKvShsTJAlsHCmetwohWga89T94LPu5tb6EyCS86BhWR1IeymnA34H+xYcBSxlcaQr+QLIg1AV/6NKIhFiKBWFMBnSjscnxx7kSiqXyZdtaOnEVYOOU8t9NidpnQ7j+cfGTPd1Y8pZf0St8z+TpOA5V7OpUNKVJuYIQMmki0jUG2iiD1IiOBjItXoAHfzXxr4WGR8jJ8Zk7oa8KYhzNtySZKFChpCMtfKdI70zI/Z0t3Gu5izxw"
      register: ec2

    - name: Add instance host to group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH connection
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 30
        timeout: 300
      loop: "{{ ec2.instances }}"

- name: Configure EC2
  hosts: launched
  connection: ssh

  tasks:
    - name: Add extras
      shell: yum-config-manager --enable extras
      become: yes
    - name: Enable docker package
      shell: amazon-linux-extras enable docker
      become: yes
    - name: Install Docker
      yum:
        name:
          - docker
          - git
        state: latest
        update_cache: yes
      become: yes
    - service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Set rights to docker
      shell: usermod -a -G docker ec2-user
      become: yes
    - name: Get project files from git
      git:
        repo: 'https://github.com/viazakh/DevOps-docker.git'
        dest: ./app
    - name: Build docker with eshop
      shell: cd app && docker build -t eshop:latest .
      become: yes
    - name: Run Docker with eshop
      shell: docker run -p 80:3000 eshop
      async: 45
      poll: 0
      become: yes
    - wait_for:
        port:
          80
