name: Build and test our eshop

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      Install:
        description: 'Install'
        required: true

      Build:
        description: 'Build'
        required: true

      Test:
        description: 'Test'
        required: true


jobs:
  # install all dependencies
  Install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 10

      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-

      - name: Install with npm
        run: npm ci

  Build:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 10

      - name: Load cached modules
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Build
        run: |
          npm rebuild node-sass --force
          npm run build -- --colors

      - name: Cache ./node_modules and ./build
          if: ${{ github.ref == 'refs/heads/master' }}
          uses: actions/cache@v2.1.6
          with:
            path: |
              ~/.npm
              ./node_modules
              ./build
            key: ${{ runner.os }}-build-${{ github.run_id }}
            restore-keys: ${{ runner.os }}-build-${{ github.run_id }}

  Test:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 10

      - name: Load cached modules
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Test
        run:
          npm run test -- --colors
